name: Alerta para Discord

on:
  push:
    branches:
      - main

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d "{\"content\": \"🚀 Novo Push no repositório: $GITHUB_REPOSITORY\nBranch: $GITHUB_REF_NAME\nAutor: $GITHUB_ACTOR\nCommit: $GITHUB_SHA\"}" $DISCORD_WEBHOOK
