name: Rodar Pytest em Pull Requests

on:
  pull_request:
    branches:
      - main # Ou o nome da branch principal do seu repositório

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # ou outra versão que você quiser

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Rodar os testes
        run: |
          pytest
